version: '3'

services:

  ms-email:
    image: postgres:14-alpine
    container_name: ms-email
    restart: on-failure
    volumes:
      - ./.docker/database/postgres/data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ms_email}
    networks:
      - ms-email

networks:
  ms-email: